import type { Metadata } from "next";
import ScrollToTop from "@/components/common/scrollToTop";
import Preload from "@/components/common/preload";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import MobileMenu from "@/components/common/mobileMenu";
import JqueryLoader from "@/components/common/JqueryLoader";
import { ToastContainer } from "react-toastify";
import ReduxProvider from "@/redux/ReduxProvider";
import "react-toastify/dist/ReactToastify.css";
import "../public/fonts/fonts.css";
import "../public/fonts/font-icons.css";
import "../public/css/bootstrap.min.css";
import "../public/css/swiper-bundle.min.css";
import "../public/css/animate.css";
import "../public/css//styles.css";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Helios Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/logo/favicon.png" />
        <link rel="apple-touch-icon-precomposed" href="/images/logo/favicon.png" />
      </head>
      <body>
        <ReduxProvider>
          <ToastContainer position="top-right" autoClose={3000} />
          <ScrollToTop />
          <Preload />
          <div id="wrapper">
            <Header />
            <MobileMenu />
            <ReduxProvider>
              {children}
            </ReduxProvider>
            <Footer />
          </div>
          <JqueryLoader />
        </ReduxProvider>
      </body>
    </html>
  );
}
