import type { Metadata } from "next";
import ScrollToTop from "@/components/common/scrollToTop";
import Preload from "@/components/common/preload";
import TopBar from "@/components/common/topBar";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import MobileMenu from "@/components/common/mobileMenu";
import JqueryLoader from "@/components/common/JqueryLoader";
import "./globals.css";

export const metadata: Metadata = {
  title: "Helios Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/fonts/fonts.css" />
        <link rel="stylesheet" href="/fonts/font-icons.css" />
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/swiper-bundle.min.css" />
        <link rel="stylesheet" href="/css/animate.css" />
        <link rel="stylesheet" type="text/css" href="/css/styles.css" />
        <link rel="shortcut icon" href="/images/logo/favicon.png" />
        <link rel="apple-touch-icon-precomposed" href="/images/logo/favicon.png" />
      </head>
      <body>
        <ScrollToTop />
        <Preload />
        <div id="wrapper">
          {/* <TopBar /> */}
          <Header />
          <MobileMenu />
          {children}
          <Footer />
        </div>
        <JqueryLoader />
      </body>
    </html>
  );
}
