export const collectionBanners = [
  {
    id: 1,
    image: "/images/2.webp",
    title: "Ergonomic Chair Sale",
    description: "Reserved for long work hours.",
    titleLink: "/products/100",
    buttonText: "Explore Collection",
    buttonLink: "/products/100",
    delayTitle: "0s",
    delayBtn: "0.2s",
  },
  {
    id: 2,
    image: "/images/4.gif",
    title: "Storage Cabinet Deals",
    description: "Reserved for organized workspaces.",
    titleLink: "/categories/100",
    buttonText: "View All Products",
    buttonLink: "/products/100",
    delayTitle: "0s",
    delayBtn: "0.2s",
  },
  {
    id: 3,
    image: "/images/6.webp",
    title: "Super Sale Up To 50%",
    description: "Reserved for special occasions",
    titleLink: "/products/100",
    buttonText: "Explore Collection",
    buttonLink: "/categories/100",
    delayTitle: "0s",
    delayBtn: "0.2s",
  },
];