export const categoryData = [
  {
    id: 1,
    title: "Desks Woods",
    image: "images/section/categories-1.jpg",
    items: 12,
    slug: "/categories/69c385cd6d44b35f3b6c0871",
    delay: "0s",
  },
  {
    id: 2,
    title: "Office Chairs",
    image: "images/section/categories-2.jpg",
    items: 35,
    slug: "/categories/69ba2adbfe394651ba158bed",
    delay: "0.1s",
  },
  {
    id: 3,
    title: "Storage Office",
    image: "images/section/categories-3.jpg",
    items: 28,
    slug: "/categories/100",
    delay: "0.2s",
  },
  {
    id: 4,
    title: "Decor Office",
    image: "images/section/categories-4.jpg",
    items: 34,
    slug: "/categories/100",
    delay: "0.3s",
  },
  {
    id: 5,
    title: "Lighting",
    image: "images/section/categories-5.jpg",
    items: 21,
    slug: "/categories/100",
    delay: "0.4s",
  },
  {
    id: 6,
    title: "Accessories",
    image: "images/section/categories-6.jpg",
    items: 18,
    slug: "/categories/100",
    delay: "0.5s",
  },
];
